apiVersion: v1
entries:
  castai-k8s-version-upgrader:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-10-08T09:13:48.802093-04:00"
    description: A Helm chart for CAST AI Node Refresher CronJob
    digest: c4e68748c01dfdd126077d7e883ead135b38360281f7df8e3ea949de8af2df37
    name: castai-k8s-version-upgrader
    type: application
    urls:
    - castai-k8s-version-upgrader-0.1.0.tgz
    version: 0.1.0
generated: "2024-10-08T09:13:48.801147-04:00"
