{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "castai-node-replicate.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "castai-node-replicate.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "castai-node-replicate.serviceAccountName" . }}
  namespace: castai-agent
{{- end }}
