apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "castai-node-replicate.fullname" . }}
  namespace: castai-agent
spec:
  schedule: {{ .Values.replicateJob.schedule | quote }}
  timeZone: {{ .Values.replicateJob.timeZone }}
  successfulJobsHistoryLimit: {{ .Values.replicateJob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.replicateJob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.replicateJob.backoffLimit }}
      template:
        metadata:
          labels:
            app: {{ include "castai-node-replicate.fullname" . }}
        spec:
          serviceAccountName: {{ include "castai-node-replicate.serviceAccountName" . }}
          restartPolicy: Never
          terminationGracePeriodSeconds: 60
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.replicateJob.image.repository }}:{{ .Values.replicateJob.image.tag }}"
            imagePullPolicy: {{ .Values.replicateJob.image.pullPolicy }}
            env:
            {{- range $key, $value := .Values.replicateJob.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            resources:
{{ toYaml .Values.replicateJob.resources | indent 14 }}
